### ISSUE TITLE
How to modify dtb for phicomm n1?

### ISSUE THREAD

**Issue by JasonChen89** [xe5700/kvmd-armbian#11]
Hello, I have a phicomm n1 box.
Current I had installed armbian(bullseye). The kernel of it supports otg.
But I don't know how to modify dtb file to support otg feature.
Could you provide the dtb or dts file of phicomm n1? Thanks!

root@amlogic:/boot#  grep -i otg config-5.4.108-flippy-56+o
CONFIG_USB_OTG=y
#CONFIG_USB_OTG_WHITELIST is not set
#CONFIG_USB_OTG_BLACKLIST_HUB is not set
CONFIG_USB_OTG_FSM=m
CONFIG_USB_FOTG210_HCD=m
CONFIG_USB_FOTG210_UDC=m

root@amlogic:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by xe5700** [comment]
You can change USB mode to peripheral for dtb file, looks you uses flippy armbian, its kernel enabled OTG feature , you need not to rebuild kernel.

**Comment by JasonChen89** [comment]
The kernel 5.4.108 for s905d has not applied this patch. OTG function works abnormal.
https://patchwork.kernel.org/project/linux-usb/cover/20200416121910.12723-1-narmstrong@baylibre.com/

After I update the kernel version to 5.15 and modify dtb file as you say, it works!
