### ISSUE TITLE
A lot of mistakes

### ISSUE THREAD

**Issue by wzooroo** [xe5700/kvmd-armbian#22]
There are a lot of errors during installation (Tell me, will this affect the work?
Orange Pi one.

`grep: /etc/kvmd/override.yaml: No such file or directory
./.tmp.kvmd-install.sh: line 56: /etc/kvmd/override.yaml: No such file or directory
./.tmp.kvmd-install.sh: line 44: cd: /etc/kvmd/nginx/ssl: No such file or directory
cp: target '/etc/kvmd/vnc/ssl/' is not a directory
sed: can't read /etc/udev/rules.d/99-kvmd.rules: No such file or directory`

`-> Apply patches
./patches/custom/old-kernel-msd/apply.sh: line 5: cd: /kvmd-3.142-py*.egg/: No such file or directory
error: kvmd/aiohelpers.py: No such file or directory
error: kvmd/apps/otg/__init__.py: No such file or directory
error: kvmd/apps/otgmsd/__init__.py: No such file or directory
error: kvmd/plugins/msd/otg/__init__.py: No such file or directory
error: kvmd/plugins/msd/otg/drive.py: No such file or directory`

**Comment by peacokswiss** [comment]
i made few fixes in this projekt...   

http://www.industrie-optimierer.ch/tmp/PiKVM/PiKVM_OrangePizero2/Readme.txt
Some PIC/DOKUS:
http://www.industrie-optimierer.ch/tmp/PiKVM/PiKVM_OrangePizero2/

**Comment by peacokswiss** [comment]
@wzooroo    your problem ist comming from apt-key from this page project..   apt-key don't work anymore,.  so you can't get rpi4  source....    so you try install  empty tar.xz ;)  hehe,, so the only way is ,.  use my scripts for this project here in...  ok  regards....

**Comment by peacokswiss** [comment]
Schoeb  gugus :)

**Comment by wzooroo** [comment]
There is the OrangePi Zero 2 H616 project. Is this application information for H3 CPU?
Or will everything have to be redone?

**Comment by wzooroo** [comment]
Thanks, I'll give it a try!

**Comment by wzooroo** [comment]
[http://www.industrie-optimierer.ch/tmp/PiKVM/PiKVM_OrangePiOne/Readme.txt](url)

> wget http://www.industrie-optimierer.ch/tmp/PiKVM/PiKVM_OrangePizero2/install.sh
wget http://www.industrie-optimierer.ch/tmp/PiKVM/PiKVM_OrangePizero2/config.sh
chmod +x install.sh
sync
./install.sh


Third Boot:
-----------
cd kvmd-armbian
./install.sh

Run ./install.sh twice ?

**Comment by wzooroo** [comment]
The starting problem has been solved!
But now there is no terminal in KVM(
And there is no way to mount iso images.
And where can I see which gpio pins are used?

**Comment by peacokswiss** [comment]
He man,  this is a issue Site, the python Stuff ist ok,... , this is not a Forum..  

Anyone who can read has a clear advantage

I told you,, first make a Armbian OS on the sdcard,  and the dtb (manipulatet on it) befor first boot.

Then go the readme for you.

On the Third boot :  cd kvmd-armbian  and   ./install.sh

If ending this second ./install.sh you shoot see some blue line..  make a Reboot,  and you have a graphical webinterface for PiKVM..

All other Stuff is explained in  http://www.industrie-optimierer.ch/tmp/PiKVM/PiKVM_OrangePizero2/  also the  http://www.industrie-optimierer.ch/tmp/PiKVM/PiKVM_OrangePizero2/kvmd-armbian_GPIO_ATX_Interface.pdf

Only to activate ATX GPIO is a bad idee...      ,  shure can end in 500 Interal Server Error


Anyone who can read has a clear advantage

ISO/IMG Files... i don't know if you read the ,,  shrink the sdcard back to maybee 5GB,  then make a new Partition,  then you can filled in /etc/fstab  and activaten in override.yaml   ,,  ist also in the Readme from the H616,  but work for all (RockPi, OrangePi whatever....)   so you have a lot of reading now.   

Just activations without reading cleary ending in not working Systems...

This for me the ending in this issue..  ok by

**Comment by wzooroo** [comment]
Man, I realize you were born with your shirt on!)
I got everything working except ATX(
I did what http://www.industrie-optimierer.ch/tmp/PiKVM/PiKVM_OrangePizero2/kvmd-armbian_GPIO_ATX_Interface.pdf says.

> Activate ATX Function
nano /etc/kvmd/override.yaml
atx:
type: gpio
Change just from disabled to gpio, save it
maybe make a sync command, reboot.
Or restart all kvmd services, i prefer reboot.

So it's not my problem) 
But thanks for the answers!
I'll try to figure it out myself!

**Comment by peacokswiss** [comment]
There i sayd,,   for H2/H3/H5  Cpu's  you need using the online Calculator to fit the pins.. !!
----Ursprüngliche Nachricht----
Von : ***@***.***
Datum : 20/11/2023 - 17:27 (MN)
An : ***@***.***
Cc : ***@***.***, ***@***.***
Betreff : Re: [xe5700/kvmd-armbian] A lot of mistakes (Issue #22)
Man, I realize you were born with your shirt on!)
 I got everything working except ATX(
 I did what http://www.industrie-optimierer.ch/tmp/PiKVM/PiKVM_OrangePizero2/kvmd-armbian_GPIO_ATX_Interface.pdf says.
 
Activate ATX Function
 nano /etc/kvmd/override.yaml
 atx:
 type: gpio
 Change just from disabled to gpio, save it
 maybe make a sync command, reboot.
 Or restart all kvmd services, i prefer reboot.
So it's not my problem)
 But thanks for the answers!
 I'll try to figure it out myself!

**Comment by peacokswiss** [comment]
https://jsfiddle.net/tuav7f6q/1/
if you read my  ATX PDF,, and on witch file you have to places on....
Anyone who can read has a clear advantage
So first definied you pins your self,, by the Calcluator,, is descriped in the  
http://www.industrie-optimierer.ch/tmp/PiKVM/PiKVM_OrangePizero2/kvmd-armbian_GPIO_ATX_Interface.pdf
then you able to activatet it on the override.yaml.. not befor !!!
shittt,  shitt, is simple
----Ursprüngliche Nachricht----
Von : ***@***.***
Datum : 20/11/2023 - 17:27 (MN)
An : ***@***.***
Cc : ***@***.***, ***@***.***
Betreff : Re: [xe5700/kvmd-armbian] A lot of mistakes (Issue #22)
Man, I realize you were born with your shirt on!)
 I got everything working except ATX(
 I did what http://www.industrie-optimierer.ch/tmp/PiKVM/PiKVM_OrangePizero2/kvmd-armbian_GPIO_ATX_Interface.pdf says.
 
Activate ATX Function
 nano /etc/kvmd/override.yaml
 atx:
 type: gpio
 Change just from disabled to gpio, save it
 maybe make a sync command, reboot.
 Or restart all kvmd services, i prefer reboot.
So it's not my problem)
 But thanks for the answers!
 I'll try to figure it out myself!
