### ISSUE TITLE
kvmd user not created by install.sh

### ISSUE THREAD

**Issue by jordankoehn** [xe5700/kvmd-armbian#27]
Part one runs successfully. No errors are reported, yet stage two doesn't run since kvmd user is not in /etc/passwd. I've read through the script yet it seems to me none of the steps should create the user, yet it's alluded [here](https://github.com/xe5700/kvmd-armbian/blob/master/install.sh#L570) that one should be created by the script

Using a brand new install of armbian jammy on an orange pi zero

**Comment by peacokswiss** [comment]
Tray my install script..   ok i go check the v308 code pikvm also.

But in true, i go still stop my coding for this project.   But for now check my code...

https://github.com/xe5700/kvmd-armbian/issues/12

**Comment by peacokswiss** [comment]
PiKVM always only uses the latest libraries.
They probably do this specifically so you can sell their hardware.

There's nothing you can't do with Bookwoorm or Ubuntu LTS, except for the modern libraries.

Even if they use the latest libraries, there is no added value for the user, so it has to be political, sales strategic.

It would be time for a fork that runs on the stable official distros Debian/Ubuntu.

This is the point where I stop my involvement with xe5700.


OK Bye

by habby

**Comment by jordankoehn** [comment]
https://github.com/Prototyped/pikvm-container worked for me on orange pi zero using docker (usb hdmi only). For a basic OS agnostic keyboard/mouse/usb hdmi installation that may be our best bet. However, keyboard/mouse isn't working for me and I think my system is to blame and not the container. I installed https://github.com/jacobbar/fruity-pikvm natively with the same result. pikvm-docker installed on an orange pi 2 might work flawlessly, it might not. I'm not sure why keyboard/mouse isn't working on orange pi zero 1 for me. OTG is set up correctly. My last effort is getting this repo working to debug my keyboard/mouse issue

**Comment by jordankoehn** [comment]
Working after installing on a fresh install of debian bookworm using [this PR's](https://github.com/xe5700/kvmd-armbian/pull/25) changes. Keyboard, mouse, and video work
